default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: true
  username: root
  password:

development:
  <<: *default
  database: multi_schema_rails_sample_development_hoge

test:
  <<: *default
  database: multi_schema_rails_sample_test_hoge
